# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do
  desc "Push a new release build to the App Store"
  lane :release do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_app_store(
      api_key_path: ".keys/fastlane_key.json",
      platform: "mac",
      skip_metadata:false,
      force: true,
      automatic_release:true,
      skip_screenshots:true,
      reject_if_possible:true,
      precheck_include_in_app_purchases:false,
      submission_information:{
        export_compliance_uses_encryption:false,
        export_compliance_encryption_updated:false,
        add_id_info_uses_idfa:false
      }
    )
  end
end
