/// Flutter icons DestinyIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DestinyIcons
///      fonts:
///       - asset: fonts/DestinyIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DestinyIcons {
  DestinyIcons._();

  static const _kFontFam = 'DestinyIcons';

  static const IconData ghost = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData leviathan_axes = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData leviathan_cup = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData leviathan_dogs = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData leviathan_sun = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData steam = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData class_titan = const IconData(0xe900, fontFamily: _kFontFam);
  static const IconData class_hunter = const IconData(0xe901, fontFamily: _kFontFam);
  static const IconData class_warlock = const IconData(0xe902, fontFamily: _kFontFam);
  static const IconData destiny = const IconData(0xe903, fontFamily: _kFontFam);
  static const IconData power = const IconData(0xe904, fontFamily: _kFontFam);
  static const IconData platform_xbox = const IconData(0xe905, fontFamily: _kFontFam);
  static const IconData platform_playstation = const IconData(0xe906, fontFamily: _kFontFam);
  static const IconData platform_blizzard = const IconData(0xe907, fontFamily: _kFontFam);
  static const IconData damage_kinetic = const IconData(0xe908, fontFamily: _kFontFam);
  static const IconData damage_arc = const IconData(0xe909, fontFamily: _kFontFam);
  static const IconData damage_solar = const IconData(0xe90a, fontFamily: _kFontFam);
  static const IconData damage_void = const IconData(0xe90b, fontFamily: _kFontFam);
  static const IconData ammo_primary = const IconData(0xe90c, fontFamily: _kFontFam);
  static const IconData ammo_special = const IconData(0xe90d, fontFamily: _kFontFam);
  static const IconData ammo_heavy = const IconData(0xe90e, fontFamily: _kFontFam);
}
