# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
fastlane_require 'dotenv'

before_all do
  Dotenv.overload '.env'
end

platform :android do
  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    upload_to_play_store(
      aab: './build/app/outputs/bundle/release/app-release.aab',
      skip_upload_screenshots: true,
      skip_upload_images: true,
      skip_upload_metadata: true,
      track:'beta'
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    upload_to_play_store(
      aab: './build/app/outputs/bundle/release/app-release.aab',
      skip_upload_screenshots: true,
      skip_upload_images: true,
      skip_upload_metadata: true,
      track:'production'
    )
  end
end

platform :ios do
  desc "Setup certificates before doing anything"
  private_lane :setup_api_key do
    app_store_connect_api_key(
      in_house: false,
      key_id: ENV["APPSTORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APPSTORE_CONNECT_ISSUER_ID"],
      key_filepath: ENV["APPSTORE_CONNECT_KEY_FILE"],
    )
  end

  desc "Build iOS app for distribution"
  lane :build do
    setup_api_key
    if is_ci
      create_keychain(
        name: ENV['MATCH_KEYCHAIN_NAME'],
        password: ENV["MATCH_KEYCHAIN_PASSWORD"],
        default_keychain: false,
        unlock: true,
        timeout: 3600,
        add_to_search_list: true,
        lock_when_sleeps: false
      )
    end
    match(
      type: "appstore",
      app_identifier: ENV["APPLE_APP_IDENTIFIER"],
      git_url: ENV["MATCH_GIT_URL"],
      readonly: is_ci
    )
    update_project_team(
      path: "ios/Runner.xcodeproj",
      teamid: ENV["APPLE_TEAM_ID"]
    )
    update_project_provisioning(
      xcodeproj: "ios/Runner.xcodeproj",
      profile: ENV["sigh_#{ENV["APPLE_APP_IDENTIFIER"]}_appstore_profile-path"],
      build_configuration: "Release",
      code_signing_identity: "iPhone Distribution"
    )
    build_app(
      workspace: "ios/Runner.xcworkspace",
      scheme: "Runner",
      output_directory:"build/ios",
      output_name: "LittleLight.ipa",
      export_method: "app-store"
    )
  end

  desc "Deploy iOS version to app store (manual release)"
  lane :beta do
      setup_api_key
      upload_to_app_store(
      ipa: "build/ios/LittleLight.ipa",
      skip_screenshots: true,
      skip_metadata: true,
      force: true,
      precheck_include_in_app_purchases: false,
      reject_if_possible: true,
      automatic_release: false,
      metadata_path: "fastlane/metadata/ios",
      submission_information:{
        export_compliance_uses_encryption: false,
        export_compliance_encryption_updated: false,
        add_id_info_uses_idfa: false,
      }
    )
  end

  desc "Deploy iOS version to app store (automatic release)"
  lane :deploy do
      setup_api_key
      upload_to_app_store(
      ipa: "build/ios/LittleLight.ipa",
      skip_screenshots: true,
      skip_metadata: true,
      force: true,
      precheck_include_in_app_purchases: false,
      reject_if_possible: true,
      automatic_release: true,
      metadata_path: "fastlane/metadata/ios",
      submission_information:{
        export_compliance_uses_encryption: false,
        export_compliance_encryption_updated: false,
        add_id_info_uses_idfa: false,
      }
    )
  end
end