# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/
languages(['de-DE', 'en-US', 'es-ES', 'fr-FR', 'it', 'ja', 'pt-BR'])