import 'package:json_annotation/json_annotation.dart';

enum ClarityClassNames {
  @JsonValue('spacer')
  Spacer,
  @JsonValue('pve')
  Pve,
  @JsonValue('pvp')
  Pvp,
  @JsonValue('breakSpaces')
  BreakSpaces,
  @JsonValue('background_2')
  Background2,
  @JsonValue('yellow')
  Yellow,
  @JsonValue('formula')
  Formula,
  @JsonValue('wide')
  Wide,
  @JsonValue('heavy')
  Heavy,
  @JsonValue('primary')
  Primary,
  @JsonValue('special')
  Special,
  @JsonValue('green')
  Green,
  @JsonValue('enhancedArrow')
  EnhancedArrow,
  @JsonValue('title')
  Title,
  @JsonValue('solar')
  Solar,
  @JsonValue('strand')
  Strand,
  @JsonValue('arc')
  Arc,
  @JsonValue('void')
  Void,
  @JsonValue('stasis')
  Stasis,
  @JsonValue('link')
  Link,
  @JsonValue('overload')
  Overload,
  @JsonValue('barrier')
  Barrier,
  @JsonValue('hunter')
  Hunter,
  @JsonValue('titan')
  Titan,
  @JsonValue('warlock')
  Warlock,
  @JsonValue('bold')
  Bold,
  @JsonValue('blue')
  Blue,
  @JsonValue('unstoppable')
  Unstoppable
}
