#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/marquesini/sdks/flutter-master"
export "FLUTTER_APPLICATION_PATH=/Users/marquesini/workspace/littlelight_desktop"
export "FLUTTER_TARGET=lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/marquesini/sdks/flutter-master/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=1.7.10"
export "FLUTTER_BUILD_NUMBER=107010"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=false"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
