# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

fastlane_version "2.39.2"

default_platform :android

platform :android do
  before_all do
    
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    supply(
      metadata_path:'../translations/metadata/android',
      aab:'../build/app/outputs/bundle/release/app.aab',
      skip_upload_screenshots:true,
      skip_upload_metadata:true,
      skip_upload_images:true,
    )
    supply(
      metadata_path:'../translations/metadata/android',
      skip_upload_screenshots:true,
      skip_upload_images:true
    )
  end

  desc "Download metadata from google play"
  lane :download_metadata do
    download_from_play_store(
      metadata_path:'../translations/metadata/android',
    )
  end

  desc "Upload metadata to google play"
  lane :upload_metadata do
    supply(
      metadata_path:'../translations/metadata/android',
    )
  end

  
end