name: Format and generate on push

on:
  push:
    branches:
      - format-test
  workflow_dispatch:
  
jobs:
  format:
    if: github.event.pull_request.head.repo.full_name == LittleLightForDestiny/littlelight
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      
      
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Download pub dependencies
        run: dart pub get

      - name: Flutter Build
        run: dart pub run build_runner build --delete-conflicting-outputs
      
      - name: Flutter Format
        run: dart format --line-length 120 --fix ./lib
        
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'LittleLightBot'
          git config --global user.email 'littlelight-bot@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.BOT_PAT }}@github.com/${{ github.repository }}
          git commit -am "Code fixes"
          git push