name: Publish to Microsoft Store

on:
  workflow_call:
    secrets:
      AZURE_AD_TENANT_ID:
        required: true
      AZURE_AD_CLIENT_ID:
        required: true
      AZURE_AD_CLIENT_SECRET:
        required: true
      MS_STORE_SELLER_ID:
        required: true
      MSIX_CONFIG:
        required: true

  workflow_dispatch:
    inputs:
      track:
        required: true
        description: Release track
        type: choice
        options:
          - "production"
          - "beta"
        default: "production"
jobs:
  macos-app-store:
    name: Publish to Microsoft app store
    runs-on: windows-latest

    steps:
      - name: Defines variables according to triggers
        id: variables
        shell: bash
        run: |
          if [ "${{ github.event_name }}" == "release" ] 
          then
            if [ "${{ github.event.release.prerelease }}" == true ]
            then
              echo "track=beta" >> $GITHUB_STATE
            else
              echo "track=production" >> $GITHUB_STATE
            fi
            echo "head_ref=main" >> $GITHUB_STATE"
          fi

          if [ "${{ github.event_name }}" == "workflow_dispatch" ] 
          then
            echo "track=${{ github.event.inputs.track }}" >> $GITHUB_STATE
            echo "head_ref=${{ github.head_ref }}" >> $GITHUB_STATE"
          fi

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.variables.outputs.head_ref }}

      - name: Download MSIX config
        id: msix_config
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: msix.yaml
          encodedString: ${{ secrets.MSIX_CONFIG }}

      - name: Append MSIX config to pubspec.yaml
        run: cat ${{ steps.msix_config.outputs.filePath }} >> {{github.workspace}}/pubspec.yaml
        shell: bash

      - name: Setup MS Store Developer CLI
        uses: microsoft/setup-msstore-cli@v1
      
      - name: Configure MS Store credentials
        run: msstore reconfigure --tenantId ${{ secrets.AZURE_AD_TENANT_ID }} --clientId ${{ secrets.AZURE_AD_CLIENT_ID }} --clientSecret ${{ secrets.AZURE_AD_CLIENT_SECRET }} --sellerId ${{ secrets.MS_STORE_SELLER_ID }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.5"

      - name: Create assets/_env
        run: |
          echo "${{ secrets.FLUTTER_DOTENV }}" > assets/_env

      - name: Cache pub dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Download pub dependencies
        run: flutter pub get
      
      - name: Build via Flutter
        run: flutter build windows --release

      - uses: actions/upload-artifact@v1
        with:
          name: windows-standalone
          path: ${{ github.workspace }}/build/windows/runner/Release

      - name: Create MSIX package
        run: msstore package

      - name: Publish MSIX to the Microsoft Store
        run: msstore publish -v

      
