name: Publish to Google Play

on:
  workflow_call:
    inputs:
      track:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      track:
        required: true
        description: Release track
        type: choice
        options:
          - "production"
          - "beta"
        default: "production"

jobs:
  google-play:
    name: Publish to Google Play
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Defines variables according to triggers
        id: variables
        run: |
          if [ "${{ github.event_name }}" == "workflow_call" ] 
          then
            echo "::set-output name=track::${{ github.event.inputs.track }}"
          fi
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] 
          then
            echo "::set-output name=track::${{ inputs.track }}"
          fi

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.8.1"

      - name: Create assets/_env
        run: |
          echo "${{ secrets.FLUTTER_DOTENV }}" > assets/_env

      - name: Create google-services.json
        run: |
          echo '${{ secrets.ANDROID_GOOGLE_SERVICES_JSON }}' > android/app/google-services.json

      - name: Cache pub dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Download pub dependencies
        run: flutter pub get

      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: release.keystore
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Create release.properties
        run: |
          mkdir android/.keys
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/.keys/release.properties
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/.keys/release.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/.keys/release.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/.keys/release.properties

      - name: Build Android App Bundle
        run: flutter build appbundle

      - name: Cache bundle dependencies
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Download bundle dependencies
        run: |
          gem install bundler:2.0.2
          bundle config path vendor/bundle
          bundle install

      - name: Release to Google Play (beta)
        if: steps.variables.outputs.track == "beta"
        env:
          SUPPLY_PACKAGE_NAME: ${{ secrets.SUPPLY_PACKAGE_NAME }}
          SUPPLY_JSON_KEY_DATA: ${{ secrets.SUPPLY_JSON_KEY_DATA }}
        run: |
          bundle exec fastlane android beta

      - name: Release to Google Play (production)
        if: steps.variables.outputs.track == "production"
        env:
          SUPPLY_PACKAGE_NAME: ${{ secrets.SUPPLY_PACKAGE_NAME }}
          SUPPLY_JSON_KEY_DATA: ${{ secrets.SUPPLY_JSON_KEY_DATA }}
        run: |
          bundle exec fastlane android deploy
