name: Publish to Microsoft Store

on:
  workflow_call:
    secrets:
      AZURE_AD_TENANT_ID:
        required: true
      AZURE_AD_CLIENT_ID:
        required: true
      AZURE_AD_CLIENT_SECRET:
        required: true
      MS_STORE_SELLER_ID:
        required: true

  workflow_dispatch:
    inputs:
      track:
        required: true
        description: Release track
        type: choice
        options:
          - "production"
          - "beta"
        default: "production"

jobs:
  windows-store:
    name: Publish to Microsoft app store
    runs-on: windows-latest

    steps:
      - name: Defines variables according to triggers
        id: variables
        shell: bash
        run: |
          if [ "${{ github.event_name }}" == "release" ] 
          then
            if [ "${{ github.event.release.prerelease }}" == true ]
            then
              echo "track=beta" >> $GITHUB_OUTPUT
            else
              echo "track=production" >> $GITHUB_OUTPUT
            fi
            echo "head_ref=main" >> $GITHUB_OUTPUT
            echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          fi

          if [ "${{ github.event_name }}" == "workflow_dispatch" ] 
          then
            echo "track=${{ github.event.inputs.track }}" >> $GITHUB_OUTPUT
            echo "head_ref=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          fi

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.variables.outputs.head_ref }}

      - name: Setup MS Store Developer CLI
        uses: microsoft/setup-msstore-cli@v1

      - name: Configure MS Store credentials
        run: msstore reconfigure --tenantId ${{ secrets.AZURE_AD_TENANT_ID }} --clientId ${{ secrets.AZURE_AD_CLIENT_ID }} --clientSecret ${{ secrets.AZURE_AD_CLIENT_SECRET }} --sellerId ${{ secrets.MS_STORE_SELLER_ID }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.6"

      - name: Create assets/_env
        shell: bash
        run: |
          echo "${{ secrets.FLUTTER_DOTENV }}" > assets/_env

      - name: Cache pub dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Download pub dependencies
        run: flutter pub get

      - name: Build via Flutter
        run: flutter build windows --release

      - name: Upload build to workflow run
        uses: actions/upload-artifact@v1
        with:
          name: LittleLight-windows
          path: ${{ github.workspace }}/build/windows/x64/runner/Release

      - name: Create release zip
        if: steps.variables.outputs.version != ''
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: "zip"
          filename: "LittleLight-windows-${{ steps.variables.outputs.version }}.zip"
          path: ${{ github.workspace }}/build/windows/x64/runner/Release

      - name: Upload build to Github Release
        uses: softprops/action-gh-release@v1
        if: steps.variables.outputs.version != ''
        with:
          tag_name: ${{ steps.variable.outputs.version }}
          files: "LittleLight-windows-${{ steps.variables.outputs.version }}.zip"

      - name: Create MSIX package
        if: steps.variables.outputs.track == 'production'
        run: msstore package

      - name: Publish MSIX to the Microsoft Store
        if: steps.variables.outputs.track == 'production'
        run: msstore publish -v -i ./build/windows/x64/runner/Release
