name: Release App

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version
        required: true

      changelog:
        type: string
        description: What's new ?
        required: true

      track:
        required: true
        description: Release track
        type: choice
        options:
          - "production"
          - "beta"
        default: "production"

jobs:
  version-update:
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Defines variables according to triggers
        id: variables
        run: |
          if [ "${{ github.event_name }}" == "release" ] 
          then
            CHANGELOG="${{ github.event.release.body }}"
            CHANGELOG="${CHANGELOG//'%'/'%25'}"
            CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
            CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
            echo "::set-output name=version::${{ github.event.release.tag_name }}"
            echo "::set-output name=changelog::${CHANGELOG}"
            if [ "${{ github.event.release.prerelease }}" == true ]
            then
              echo "::set-output name=track:beta"
            else
              echo "::set-output name=track:production"
            fi
          fi
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] 
          then
            CHANGELOG="${{ github.event.inputs.changelog }}"
            CHANGELOG="${CHANGELOG//'%'/'%25'}"
            CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
            CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
            echo "::set-output name=version::${{ github.event.inputs.version }}"
            echo "::set-output name=changelog::${CHANGELOG}"
            echo "::set-output name=track::${{ github.event.inputs.track }}"
          fi

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
          cache-dependency-path: .github/workflows/scripts/package-lock.json

      - name: Updates version and changelog
        run: npm ci
        working-directory: .github/workflows/scripts/

      - name: Updates version and changelog
        run: npm run version-update -- --version=${{ steps.variables.outputs.version }} --changelog="${{ steps.variables.outputs.changelog }}"
        working-directory: .github/workflows/scripts/

      - name: Add changes to commit
        run: |
          git add pubspec.yaml
          git add CHANGELOG.md
          git add fastlane

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'LittleLightBot'
          git config --global user.email 'littlelight-bot@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.BOT_PAT }}@github.com/${{ github.repository }}
          git commit -am "Updating pubspec and changelogs to version ${{steps.variables.outputs.version}}"
          git push

  publish-google-play:
    uses: ./.github/workflows/publish-google-play.yml
    needs: [version-update]
    with:
      track: ${{ steps.variables.outputs.version }}
    secrets:
      FLUTTER_DOTENV: ${{ secrets.FLUTTER_DOTENV }}
      ANDROID_GOOGLE_SERVICES_JSON: ${{ secrets.ANDROID_GOOGLE_SERVICES_JSON }}
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      SUPPLY_PACKAGE_NAME: ${{ secrets.SUPPLY_PACKAGE_NAME }}
      SUPPLY_JSON_KEY_DATA: ${{ secrets.SUPPLY_JSON_KEY_DATA }}
