name: Release App

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version
        required: true

      changelog:
        type: string
        description: What's new ?
        required: true

      track:
        required: true
        description: Release track
        type: choice
        options:
          - "production"
          - "beta"
        default: "production"

jobs:
  version-update:
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    outputs:
      track: ${{ steps.variables.track }}

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_PAT }}
          ref: main

      - name: Defines variables according to triggers
        id: variables
        run: |
          if [ "${{ github.event_name }}" == "release" ] 
          then
            CHANGELOG="${{ github.event.release.body }}"
            CHANGELOG="${CHANGELOG//'%'/'%25'}"
            CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
            CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
            echo "::set-output name=version::${{ github.event.release.tag_name }}"
            echo "::set-output name=changelog::${CHANGELOG}"
          fi
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] 
          then
            CHANGELOG="${{ github.event.inputs.changelog }}"
            CHANGELOG="${CHANGELOG//'%'/'%25'}"
            CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
            CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
            echo "::set-output name=version::${{ github.event.inputs.version }}"
            echo "::set-output name=changelog::${CHANGELOG}"
          fi

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
          cache-dependency-path: .github/workflows/scripts/package-lock.json

      - name: Updates version and changelog
        run: npm ci
        working-directory: .github/workflows/scripts/

      - name: Updates version and changelog
        run: npm run version-update -- --version=${{ steps.variables.outputs.version }} --changelog="${{ steps.variables.outputs.changelog }}"
        working-directory: .github/workflows/scripts/

      - name: Add changes to commit
        run: |
          git add pubspec.yaml
          git add CHANGELOG.md
          git add fastlane

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updating pubspec and changelogs to version ${{steps.variables.outputs.version}}
          commit_user_name: LittleLightBot
          commit_user_email: LittleLightBot@users.noreply.github.com

  publish-google-play:
    uses: ./.github/workflows/publish-google-play.yml
    needs: [version-update]
    secrets:
      FLUTTER_DOTENV: ${{ secrets.FLUTTER_DOTENV }}
      ANDROID_GOOGLE_SERVICES_JSON: ${{ secrets.ANDROID_GOOGLE_SERVICES_JSON }}
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      SUPPLY_PACKAGE_NAME: ${{ secrets.SUPPLY_PACKAGE_NAME }}
      SUPPLY_JSON_KEY_DATA: ${{ secrets.SUPPLY_JSON_KEY_DATA }}

  publish-ios:
    uses: ./.github/workflows/publish-ios.yml
    needs: [version-update]

    secrets:
      APPSTORE_CONNECT_KEY_ID: $ {{secrets.APPSTORE_CONNECT_KEY_ID }}
      APPSTORE_CONNECT_ISSUER_ID: $ {{secrets.APPSTORE_CONNECT_ISSUER_ID }}
      APPLE_TEAM_ID: $ {{secrets.APPLE_TEAM_ID }}
      APPLE_APP_IDENTIFIER: $ {{secrets.APPLE_APP_IDENTIFIER }}
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: $ {{secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
      MATCH_GIT_URL: $ {{secrets.MATCH_GIT_URL }}
      MATCH_PASSWORD: $ {{secrets.MATCH_PASSWORD }}
      APPLE_USERNAME: $ {{secrets.APPLE_USERNAME }}
      MATCH_KEYCHAIN_NAME: $ {{secrets.MATCH_KEYCHAIN_NAME }}
      MATCH_KEYCHAIN_PASSWORD: $ {{secrets.MATCH_KEYCHAIN_PASSWORD }}
      MATCH_GIT_API_AUTH: $ {{secrets.MATCH_GIT_API_AUTH }}
      FLUTTER_DOTENV: $ {{secrets.FLUTTER_DOTENV }}
      IOS_GOOGLE_SERVICE_INFO_PLIST_BASE64: $ {{secrets.IOS_GOOGLE_SERVICE_INFO_PLIST_BASE64 }}
      APPSTORE_CONNECT_KEY_BASE64: $ {{secrets.APPSTORE_CONNECT_KEY_BASE64 }}

  update-translations:
    uses: ./.github/workflows/update-translations.yml
    needs: [version-update]
    secrets:
      BOT_PAT: ${{ secrets.BOT_PAT }}
