name: Release App

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version
        required: true

      changelog:
        type: string
        description: what's new ?
        required: true

jobs:
  version-update:
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Defines variables according to how the workflow should behave
        id: variables
        run: |
          if[[ "${{ github.event_name }}" == "release"]] then
            echo ::set-output name=version::"${{ github.event.release.tag_name }}";
            echo ::set-output name=changelog::"${{ github.event.release.body }}";
          fi
          if[[ "${{ github.event_name }}" == "workflow_dispatch"]] then
            echo ::set-output name=version::"${{ github.event.inputs.version }}";
            echo ::set-output name=changelog::"${{ github.event.inputs.changelog }}";
          fi

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
          cache-dependency-path: .github/workflows/scripts/package-lock.json

      - name: Updates version and changelog
        run: npm ci
        working-directory: .github/workflows/scripts/

      - name: Updates version and changelog
        run: npm run version-update -- --version=${{ steps.variables.outputs.version }} --changelog=="${{ steps.variables.outputs.changelog }}"
        working-directory: .github/workflows/scripts/

      - name: Add changes to commit
        run: |
          git add pubspec.yaml
          git add CHANGELOG.md
          git add fastlane

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.BOT_PAT }}@github.com/${{ github.repository }}
          git commit -am "Updating pubspec and changelogs to version ${{env.VERSION}}"
          git push
