name: Test fastlane path

on:
  workflow_dispatch:

jobs:
  print-path:
    name: Print fastlane path
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.variables.outputs.head_ref }}

      - name: Cache bundle dependencies
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0

      - name: Download bundle dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install

      - name: Build iOS via Fastlane
        run: bundle exec fastlane ios changelogs
