name: Google Play

on:
  workflow_call:
  workflow_dispatch:

jobs:
  update-translations:
    name: Update translations
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: translations
          repository: LittleLightForDestiny/LittleLightTranslations

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
          cache-dependency-path: translations/package-lock.json

      - name: Download translation map generator dependencies
        run: npm ci
        working-directory: translations

      - name: Update translations map
        run: npm start
        working-directory: translations
