name: Update translations

on:
  workflow_call:
  workflow_dispatch:

jobs:
  update-translations:
    name: Update translations
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: translations
          repository: LittleLightForDestiny/LittleLightTranslations

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
          cache-dependency-path: translations/package-lock.json

      - name: Download translation map generator dependencies
        run: npm ci
        working-directory: translations

      - name: Update translations map
        run: npm run import
        working-directory: translations

      - name: Check for modified files
        id: git-check
        working-directory: translations
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        working-directory: translations
        run: |
          git config --global user.name 'LittleLightBot'
          git config --global user.email 'littlelight-bot@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.BOT_PAT }}@github.com/LittleLightForDestiny/LittleLightTranslations
          git commit -am "Updating translation maps"
          git push
