name: Update translations

on:
  workflow_call:
    secrets:
      BOT_PAT:
        required: true
  workflow_dispatch:

jobs:
  update-translations:
    name: Update translations
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: translations
          repository: LittleLightForDestiny/LittleLightTranslations
          token: ${{ secrets.BOT_PAT }}

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
          cache-dependency-path: translations/package-lock.json

      - name: Download translation map generator dependencies
        run: npm ci
        working-directory: translations

      - name: Update translations map
        run: npm run import
        working-directory: translations

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: translations
          commit_message: Updating translation maps
          commit_user_name: LittleLightBot
          commit_user_email: LittleLightBot@users.noreply.github.com
