name: Version update test script

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version
        required: true

      changelog:
        type: multiline
        description: what's new ?
        required: true
  
jobs:
  version-update:
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: ./github/workflows/scripts/package-lock.json
      
      - name: Updates version and changelog
        run: npm run version-update -- --version=${{github.event.inputs.version}} --changelog==${{github.event.inputs.changelog}}
        working-directory: ./github/workflows/scripts/